### ISSUE TITLE
Retrieve ISSN?

### ISSUE THREAD

**Issue by robtlx** [rbrtjwrk/scopus_harvester#1]
Hello! 

This looks like a nice tool and pretty useful for me at the moment - however, I'm pretty new in Python and I don't really understand if this is possible.

Can I use harvester to query the presence of specific ISSNs in the Scopus database? If so, could you maybe help me with constructing the query?

Thank you!

**Comment by rbrtjwrk** [comment]
Hi!

Definitely, just use the modified _scopus_get_journals_ function, for example like this:

```python
import json
import requests

def scopus_get_journal(ISSN):
    payload={
            "Accept": "application/json",
            "X-ELS-APIKey": "YOUR_API_KEY"}
    parameters={
                "issn": ISSN}
    response=requests.get("https://api.elsevier.com/content/serial/title", headers=payload, params=parameters)
    return response.json()
```

Then:

```
journal=scopus_get_journal("0007-9235")

print(journal)

{'serial-metadata-response': ...}
```

**Comment by robtlx** [comment]
Thank you for the detailed response!

This looks good, however - when I try and run it, the function returns 
{'service-error': {'status': {'statusCode': 'AUTHENTICATION_ERROR', 'statusText': 'Invalid API Key: valid apikey credentials required.'}}}

Weird.. as I have a valid API key and it's inputted properly in the X-ELS-APIKey field.

**Comment by rbrtjwrk** [comment]
Then I suggest checking one more time if the API Key is inputted correctly or contacting [Elsevier APIs Suppor Center] (https://service.elsevier.com/app/contact/supporthub/researchproductsapis/). For me, it works fine.

**Comment by rbrtjwrk** [comment]
Then I suggest checking one more time if the API Key is inputted correctly or contacting [Elsevier APIs Suppor Center](https://service.elsevier.com/app/contact/supporthub/researchproductsapis/) For me, it works fine.

**Comment by robtlx** [comment]
From what it appears, the search is not supported by the free version of the API, and it requires an Institutional Token. Once I got that and added it to my InstToken field, it worked.

Thank you again!

**Comment by rbrtjwrk** [comment]
Glad to hear you managed it out!
